### PR TITLE
Removes query string from request uri when searching for format

### PR DESCRIPTION
**Pull request by mleczakm**

### CODE REVIEW

**Comment by jacwright** [comment]
Great find. Thank you.

**Comment by mleczakm** [comment]
I've found it still has a bug - it cuts last part of a uri after a dot, form example when I've "/register/mail/test@dot.com" and path in controller registered as "/mail/$email", variable $email contains only "test@dot". I will provide a fix ASAP cause i need this in my project.

**Comment by jacwright** [comment]
How can we get it to work with extensions for formats such as `.json`? We need to still support this.

**Comment by jacwright** [comment]
If you only match against registered formats that would work. Unregistered formats add the extension back to the URL.

**Pull request merged**
