### PR TITLE
update(1.0.0)

### PR DESCRIPTION
**Pull request by simonepri**

### CODE REVIEW

**Comment by jacwright** [comment]
Conflicts. Sorry, I had already merged the other PR.

**Comment by simonepri** [comment]
The PR that you have merged created a bugged code.
I've just removed my code and left other changes.
If you don't remove my changes it will not work at all.
Check differences there's no strange edit.

**Comment by jacwright** [comment]
Could I get a +1 on #59 and we can close this one out?

**Comment by simonepri** [comment]
It's Perfect, thank you

**Pull request closed without merging**
