### PR TITLE
prepared for packagist

### PR DESCRIPTION
**Pull request by stevleibelt**
Hi jacwright,

i've added a composer.json and tried to prepare your repository to get published on (packagist)[https://packagist.org/].
Since i liked your apporach to get things done quickly (for prototyping), i would like to use it more easily in the composer comfort zone (using composer autoloading and version installing/updating).

Furthermore, i've introduced a namespace for this repository.

### CODE REVIEW

**Comment by karneaud** [comment]
Hi...i was thinking the same thing as I have used this project and find it to be delightfully easy. How is this going?

**Comment by adrienrn** [comment]
Well done !
Want to used it through composer too :), would be really cool to get this merged.

**Comment by jacwright** [comment]
This would be great. @stevleibelt, would you mind resolving the conflicts and updating the PR? I'll get this merged.

**Comment by stevleibelt** [comment]
@jacwright I will solve it in the next days.

Be ready for the pull request ;-) :-).

**Comment by stevleibelt** [comment]
Overwhelmed by [pull/40](https://github.com/jacwright/RestServer/pull/40).

**Pull request closed without merging**
