### PR TITLE
prepared for packagist / implemented usage of composer

### PR DESCRIPTION
**Pull request by stevleibelt**
This pull request solves overwhelms [pull/18](https://github.com/jacwright/RestServer/pull/18).
All jacwright has to do is, to submit this repository to packagist.org after accepting this pull request.

I've added the dependency to "zf1/zend-amf": "1.12.11" since it is used in the code.
Furthermore, I've moved the three class definitions into separate files, added the namespace "Jacwright\RestServer", adapted the example and added todo's (in general, warnings/hints from my IDE).

### CODE REVIEW

**Comment by jacwright** [comment]
This RestServer was originally created several years ago when Adobe Flash development was still alive and well. I believe we can remove the AMF format and dependencies on zf1. This would make using RestServer more palatable if it didn't come with any dependencies.

What do you think @stevleibelt?

**Comment by stevleibelt** [comment]
@jacwright 
I'm on your side with the idea to remove this dependency. If needed, we can easily extend it. 
Also having the focus on the first line of the [readme](https://github.com/jacwright/RestServer/blob/master/README.md), I would give this idea a warm welcome :-).

I can do it, when I'm back at home if you want to.

**Comment by jacwright** [comment]
That would be great! We can just use this PR for that if it works for you.

**Comment by stevleibelt** [comment]
Wow, didn't know github can handle that.
So I removed the amf support, also in the [readme](https://github.com/jacwright/RestServer/blob/master/README.md).
My head is assigned to a cold, so please read the readme and chick if I havn't removed to much.

**Comment by jacwright** [comment]
Gotta leave the PR open in order for it to be accepted. :smile:

**Comment by stevleibelt** [comment]
So is there anything I can/should do? :)

**Comment by jacwright** [comment]
Stop closing it before I can merge it. :)

**Comment by stevleibelt** [comment]
Now I get it :-D ;-).

**Comment by karneaud** [comment]
Guys.

see issue https://github.com/jacwright/RestServer/issues/37

**Pull request merged**
